### PR TITLE
_Correctly_ apply the new medal pack format

### PR DESCRIPTION
**Pull request by scooterpsu**
### Proposed changes in this pull request:

1. New medal pack format

2. Only shows when needed

3. 100% lua free

### Why should this pull request be merged?
I did things correctly this time

### Have you tested this on your own and/or in a game with other people?
My cpu hated the number of game instances I used to confirm this worked.

### CODE REVIEW

**Comment by Shockfire** [comment]
Better, but you should only be using the global "image" and "sound" value for each event if none of the other categories are satisfied. For example, there are some events which are sent to everyone but have a different meaning for the cause player.

**Comment by scooterpsu** [comment]
Ah, wasn't sure it was something that could cause an issue. Easy enough to fix.

**Comment by scooterpsu** [comment]
How's that?

**Comment by Shockfire** [comment]
Better.

Just noticed an XSS vulnerability here though: https://github.com/scooterpsu/ElDorito/blob/web-renderer/web/screens/medals/medals.js#L66. You can't trust anything in the medal JSON files because people will be downloading these from untrusted sources (reddit posts, etc.).

**Comment by scooterpsu** [comment]
Ah right, nobody can be trusted. I'll fix it.

**Comment by scooterpsu** [comment]
Fixed.

**Comment by Shockfire** [comment]
That "final XSS catch" isn't necessary. jQuery doesn't use string concatenation to build elements.

**Comment by scooterpsu** [comment]
Removed.

**Pull request merged**
