### PR TITLE
Simple commands for screen binds

### PR DESCRIPTION
**Pull request by maximumgame**
### Proposed changes in this pull request:

1. Add two console commands, Web.ShowScreen <screen name> and Web.HideScreen <screen name>

### Why should this pull request be merged?

Community created screens can set their own binds with dew.command("bind <key> web.showscreen <screen name>"....
Instead of each screen needing a hardcoded key.
Or a user can set their own binds for another screen.

### Have you tested this on your own and/or in a game with other people?
Yes, multiplayer N/A

### CODE REVIEW

**Comment by Shockfire** [comment]
Thanks for submitting this! Would you be willing to make a few changes?

- Remove the `HideScreen` command. Screens are responsible for hiding themselves.
- Move the commands into the "Game" module instead of making a new "Web" module. There's already a command in there for showing the server browser, so I'd like to keep things consistent for now and not draw too much attention to commands that most people won't need.
- Allow passing in screen data as an optional argument to the `ShowScreen` command (and defaulting to `{}` if it's not given). You need to be careful with how you handle this so that arbitrary JavaScript code can't be executed with it. Make sure to parse the argument as JSON (checking for validity) and then re-serialize it into a string.
- I was thinking that it might be a good idea to make the `ShowScreen` command host-only in order to make it harder to use custom screens to cheat. Would you agree?

**Comment by maximumgame** [comment]
Double quotes seem to be erased when commands are entered. So it gets a little hard to pass valid json without them.

I can just replace single quotes with double quotes as a workaround if that is acceptable but that seems a bit unintuitive and would need to be made clear to creators.

As for host-only, I'm not sure what the harm is in letting people use screens if they want, especially if someone creates a friends list type ui. Although there could always be a synced variable that allows or disallows the command if the host wants to allow it. But a screen could still be added to the game and overlayed without capturing the mouse whether or not this command is used.

**Comment by Shockfire** [comment]
Ah, forgot that our command parser isn't terribly robust, it's been a while <_<

Maybe what you could do is just take the arguments following the screen name and shove them into an array, e.g. `ShowScreen MyCoolScreen a b c d` would generate `{ "args": [ "a", "b", "c", "d" ] }`. This is useful because the screen show mechanism also intentionally works as a sort of messaging system between screens, because the show event will be called even if the screen is already open. Developers could use this to replicate the HideScreen command if they want a togglable screen (e.g. pass "close" as an argument and then have the screen close itself in the show event).

Unfortunately it actually is currently possible to use the screen system to cheat, since screens can do things like access internal console variables. I suppose that this is probably an issue on its own though, so we can start with always allowing custom screens for now and then change it later if we decide that it's necessary. I'll come up with a workaround for safely accessing those internal values.

**Comment by maximumgame** [comment]
I've had success adding a command flag (eCommandFlagArgsNoParse) where the args are passed as one string and used as argument[0] in the function.

This way I've been able to get double quotes and spaces passed fine.

**Pull request merged**
