### PR TITLE
Fixed blank variables not being sent over RCON

### PR DESCRIPTION
**Pull request by medsouz**
Commands will now return "" instead of an empty string when they are blank.

Simplest pull request ever.

### CODE REVIEW

**Comment by FishPhd** [comment]
Now make rcon send back console response

**Comment by no1dead** [comment]
wat it already does that.

**Comment by NoShotz** [comment]
It never did for me, if i did server.password it wouldnt remove the passoword, but if i did server.password "" it would

**Comment by Shockfire** [comment]
This doesn't do what you think it does. Using this code, if I try to remove the server password by using something like

    Server.Password ""

then it actually sets the password to two double-quotes instead of removing it.

**Comment by NoShotz** [comment]
That doesnt seem correct, as i just tested it

http://i.imgur.com/KW3seIo.png

**Comment by scooterpsu** [comment]
I think the confusion here is that it's not setting the pass to "", it's returning "" because before this code it returned a blank (which wouldn't send via rcon).

**Comment by Shockfire** [comment]
No, it actually is setting the variable value to that. Assigning to `cmd->ValueString` sets the value of the variable. This fix is in the wrong spot.

**Comment by Frankity** [comment]
add the way to send echos to the game using rcon.

**Comment by Shockfire** [comment]
@Frankity, please create separate issues for feature requests and be as specific as possible.

**Pull request closed without merging**
