### PR TITLE
Classical default colors

### PR DESCRIPTION
**Pull request by h3intensity**
**Proposed changes in this pull request:**

Change current default colors to a more classical color scheme.

**Why should this pull request be merged?**

Gives players a more "nostalgic" feeling for opening the game for the first time, as it is a very distinct set of colors.

Due to it's color scheme, players will be more open to customizing their player model right off the bat to fit something other than black.

**Have you tested this on your own and/or in a game with other people?**

N/A

### CODE REVIEW

**Comment by camden-smallwood** [comment]
It's too yellow, in my opinion.
halo-3-wallpaper-halo-chapter-1080p-012-chief -cortana -arbiter

**Comment by theTwist84** [comment]
Would it not be better to swap to a closer h3 shader in tags

**Comment by NoShotz** [comment]
this was the image the sent me of how it looks, https://cdn.discordapp.com/attachments/263741546464149505/286924291260284929/eldorado_2017-03-02_13-14-10.jpg

**Comment by h3intensity** [comment]
The colors are supposed to represent the same colors you would have by default when creating a new player profile on halo 3, not master cheif

**Comment by Clef-0** [comment]
They look good with Halo 3 armors, but most players will be starting the game with Halo Online armors and the yellowy-green looks a lot more obnoxious on them.

**Pull request closed without merging**
