### PR TITLE
Enable more aspect ratios

### PR DESCRIPTION
**Pull request by medsouz**
This disables the aspect ratio check that only allows 4:3 or 16:9 resolutions.

Based off of jackfuste's custom eldorado.exe:
http://www.wsgf.org/forums/viewtopic.php?f=95&t=30667&p=163881

### CODE REVIEW

**Comment by Shockfire** [comment]
This is fine, though there are still some issues that need to be worked out:

Scaling Issues

1. HUD scaling has some issues
2. If the game doesn't cover the whole screen, chat gets cut off.

**Comment by medsouz** [comment]
Alright, I fixed the chat issues. I did most of my testing in windowed mode, so I didn't notice that the chat is rendered based on screen coordinates instead of viewport coordinates.

Also, I looked into the HUD scaling issues and found that it looks like that normally on non-widescreen resolutions.

4:3 (1024x768): (From what I've seen in the game's code 4:3 resolutions are allowed normally. I have a 16:9 monitor so I can't really check)
1024x768

5:4 (1280x1024):
1280x1024

16:9 (1600x900):
1600x900

**Comment by jonology** [comment]
I'm downloading this now, if you tell me what to do I can test on my 21:9 ratio screen

**Comment by medsouz** [comment]
All you have to do is go into the settings screen and select your resolution.

**Comment by Shockfire** [comment]
Nice work. Do you think it's possible to hide the "visor" graphics completely if you're on a resolution where it might look bad?

**Comment by medsouz** [comment]
@camden-smallwood and I are going to be looking more into that tomorrow.

**Comment by Ernegien** [comment]
HUD item-specific opacities can be modified in the memory globals so perhaps the visor can be dynamically disabled that way. I didn't look into how the item indexes are determined; hopefully they're at least always the same within the same build.

```
var chudGlobals = game.Memory.ReadUInt32(game.TlsAddress + 0x424);
var firstHudItemOpacity = game.Memory.ReadSingle(chudGlobals + 0x184);
var secondHudItemOpacity = game.Memory.ReadSingle(chudGlobals + 0x188);
```

**Comment by medsouz** [comment]
Everything seems to work now other than the H3UI menu being too large on extremely small resolutions.

**Comment by medsouz** [comment]
I just realized that I forgot to post the tag changes needed:

```
edit 01bd
echo Tell the game to use the first HUDAttribute index for widescreen and standard instead of just widescreen.
echo I figured it would be better for mod comaptibility to just use the normal HUDAttribute instead of copying the data over to the standard attribute (index #5)
setfield hudglobals[0].hudattributes[0].ResolutionFlags 9
savechanges
exit

edit 0c1e
echo Enable UI elements on standard resolutions
setfield hudwidgets[25].bitmapwidgets[0].statedata[0]._4Resolution 9
setfield hudwidgets[25].bitmapwidgets[1].statedata[0]._4Resolution 9

setfield hudwidgets[26].bitmapwidgets[0].statedata[0]._4Resolution 9
setfield hudwidgets[26].bitmapwidgets[1].statedata[0]._4Resolution 9
setfield hudwidgets[26].bitmapwidgets[2].statedata[0]._4Resolution 9

setfield hudwidgets[27].bitmapwidgets[0].statedata[0]._4Resolution 9
setfield hudwidgets[27].bitmapwidgets[1].statedata[0]._4Resolution 9
setfield hudwidgets[27].bitmapwidgets[2].statedata[0]._4Resolution 9
setfield hudwidgets[27].bitmapwidgets[3].statedata[0]._4Resolution 9
setfield hudwidgets[27].bitmapwidgets[4].statedata[0]._4Resolution 9
setfield hudwidgets[27].bitmapwidgets[5].statedata[0]._4Resolution 9
savechanges
exit
```

**Pull request merged**
