### PR TITLE
Server.AssassinationEnabled command

### PR DESCRIPTION
**Pull request by Shad0wShayd3**
Allows for server side implementation of Assassination Animation removal, saves to config, changes in real time, syncs

### CODE REVIEW

**Comment by FishPhd** [comment]
@Shockfire do eet

**Comment by NoShotz** [comment]
we need this @Shockfire

**Comment by Shockfire** [comment]
Has this been tested in a networked game?

**Comment by Shad0wShayd3** [comment]
Why yes, it has been tested in a network game http://a.pomf.cat/ldiumg.mp4.

**Comment by theTwist84** [comment]
Unrelated
https://github.com/ElDewrito/ElDorito/blob/master/src/Modules/ModuleCamera.cpp#L380

**Comment by theweion** [comment]
Just a thought, shouldn't this be disabled by default, the assassination system is not well implemented and can be triggered by any keyboard that isn't a Laptop or Rubber-dome, effectively taking control away from the player. I am on a Cherry MX Blue it is literally impossible for my to lightly press the F key, therefore I am at a disadvantage in that situation as a result.

Also because of the specific scenario in which this event is triggered, I fear not many server hosts other than the ones that have hosted before will know about this.

**Comment by FishPhd** [comment]
I know a man with this power

**Comment by scooterpsu** [comment]
The assassinations have nothing to do with how lightly you press the button.

**Comment by Red-M** [comment]
Guys, don't shit up issue requests with shitposting, it wastes other
people's time.

**Comment by FishPhd** [comment]
@Red-M k

**Comment by Shockfire** [comment]
So here's the deal with this.

Generally we prefer that most patches be done without editing tag data, because it's more error-prone, it's often complicated, and it can make the game more difficult to mod. There are obviously some exceptions to this, but we like to find code solutions if we can. This is the reason why I've been a bit hesitant to accept this.

Zedd and I did some digging, and we found a way to disable assassinations by forcing the branch at 0x538557. This can be done by writing the bytes 90 E9 to that address.

If you're interested, I will let you update your code to use this solution. You could do this rather easily by copying how the [sprint toggle](https://github.com/ElDewrito/ElDorito/blob/master/src/Patches/Sprint.cpp) works, stripping out the irrelevant code, and changing the patch declaration to something like

    Patch disableAssassinationsPatch(0x138557, { 0x90, 0xE9 });

If you do this, then I can accept this request.

**Comment by theTwist84** [comment]
So I'm not sure @Shad0wShayd3 will like this but I did what you said @Shockfire and it works 100%

**Pull request merged**
