### PR TITLE
Teamspeak Kicking

### PR DESCRIPTION
**Pull request by rehashedsalt**
Adds a function, `kickTeamspeakClient`, that kicks clients from the Teamspeak server. It could probably be done better with `std::vector` and `std::find`, but the function to get all connected clients returns an array so I figured I'd just loop it.

### CODE REVIEW

**Comment by ElDewritoDev** [comment]
Nice work, but there are a few bugs in this which you will need to fix before we can approve it:

* You aren't enumerating over the client list correctly ([line 258 in TeamspeakServer.cpp](https://github.com/rehashedsalt/ElDorito/commit/1363712c80d5cb887d07a564b94055cc1d6ad1ed#diff-b69a10df66353e4e1a5fc693497d78f7R258)). `sizeof(listClientIDs)` is always going to return 4 because listClientIDs is a pointer. According to the TeamSpeak SDK documentation, the client ID list is null-terminated and you must loop through it until you get a null ID.
* There's a memory leak because you aren't freeing workingClientName correctly. You have to free it each iteration once you're done using it. Currently, only the last client name is going to be freed.
* listClientIDs isn't going to be freed if an error happens inside the loop.

Additionally, here are some style guidelines which we would prefer that you follow:

* You can reduce the amount of indentation in your code by negating your error conditions. For example,
```c++
if (ts3server_getClientList(1, &listClientIDs) != ERROR_ok) {
	console.consoleQueue.pushLineFromGameToUI("Kick: Error getting list of clients");
	return -1;
}
```
* Your kickTeamspeakClient() should accept a const std::string& instead of just an std::string (to avoid an unnecessary string copy).
* It isn't necessary to turn workingClientName into an std::string because comparing an std::string against a char* is valid.

**Comment by rehashedsalt** [comment]
All easy fixes. Give me a bit and I'll have a commit ready.

**Comment by rehashedsalt** [comment]
There we go. Enumeration's fixed, memory is freed right before every `return`, I switched all the error checks to negation (which does look quite nice, by the way. Thanks for that tip), `kickTeamspeakClient()` now accepts a `std::string&`, and that unnecessary cast was removed.

Did I miss anything?

**Comment by ElDewritoDev** [comment]
Much better, but you still need to make sure you free names which don't match. You could do something like this to only have to call freeMemory() on the name once:

```c++
if (ts3server_getClientVariableAsString(1, listClientIDs[a], CLIENT_NICKNAME, &workingClientName) != ERROR_ok) {
    // Error
}
bool matches = (name == workingClientName);
ts3server_freeMemory(workingClientName);
if (matches) {
    // Kick the client, etc.
}
```

**Comment by rehashedsalt** [comment]
Crap. Of course I'd miss the biggest memory leak.

The first commit fixes the `workingClientName` using your code, and the second fixes the CYA code.

**Comment by dark-c0de** [comment]
Thanks for this!

**Comment by rehashedsalt** [comment]
No problem!

**Pull request merged**
