### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by Chaosvex**
**Proposed changes in this pull request:**
Various fixes for issues flagged up by various static analysers.

**Why should this pull request be merged?**
Because it fixes potential crashes/memory leaks/other undefined behaviour oddities.

**Have you tested this on your own and/or in a game with other people?**
No.

### CODE REVIEW

**Comment by camden-smallwood** [comment]
Clean this up and I'll review it.

**Comment by Chaosvex** [comment]
What exactly do you want cleaned up? Each commit is a standalone fix for review.

**Comment by camden-smallwood** [comment]
Primarily, there's merge conflicts at the moment... and if they need to be reviewed separately, it might be a better idea to submit them as multiple condensed pull requests.

**Comment by Chaosvex** [comment]
There weren't (or shouldn't have been) any merge conflicts at the time of the PR. I don't see the need for submitting 12 PRs for small fixes that are easily reviewed in a single PR. If anybody identified a problem with any of the fixes, I would amended it in another commit.

**Comment by camden-smallwood** [comment]
Pull request reopened so you can view the conflicts.

**Comment by Chaosvex** [comment]
The conflict is from a later commit that applied one of my fixes (either coincidentally or from reviewing this PR). 

https://github.com/ElDewrito/ElDorito/commit/2081b6fe229b61de7c699d4e0a6906b89c128486#diff-dd01cfcc8c04c8e2c71752829d81183b

**Comment by camden-smallwood** [comment]
Merged

**Comment by Chaosvex** [comment]
Thanks. 👍

**Pull request merged**
