### PR TITLE
Add support for multi-team

### PR DESCRIPTION
**Pull request by unk-1**
### Proposed changes in this pull request:

1. Add support for multi-team

### Why should this pull request be merged?
multi-team

### Have you tested this on your own and/or in a game with other people?
Tested pretty extensively. Note: It will break the Scaleform scoreboard.

### CODE REVIEW

**Comment by Alex-231** [comment]
The scaleform scoreboard just needs a few tweaks it seems.
I've successfully added more colours to the scoreboard gfx, I've been unable to fully test scripting but that should be easy to fix. The game is currently checking if the team is even or odd, rather than assigning color by index.
Going to finish this over the weekend.

**Comment by camden-smallwood** [comment]
Looks good to me. Whenever the scoreboard files are finished, can you please upload them and post a link in here? We'll merge after that.

**Comment by Alex-231** [comment]
Multi team is looking good for most scenarios.

It's not flawless though.
The main issue with the scaleform scoreboard is that, when teams get unorgamized, it fails to track ranking within teams.
For example, if a player is on pink, and another is on red, the scoreboard will probably not list any players.
The issue is kind of random, sometimes it will just resolve itself and display players anyway. I've managed to pinpoint the main symptom in the scripting, the team_players_ranking vector is being populated with the new teams, but the new teams within that vector are not being populated with GL_ScoreboardRanking indices.
Again, for standard lobbies this won't be an issue, games, as long as teams are in order it works fine.

I've also resolved issues where players would duplicate on the scoreboard, added the new colors and reworked the headers to support new teams.

Tag changes will be uploaded tomorrow, just got to correct a color.

**Comment by camden-smallwood** [comment]
I'll go ahead and merge this. Chances are, at some point in the future, we won't be using the Scaleform interface anymore. If you can get the vfsl changes to work correctly @Alex-231 then awesome!

**Comment by Alex-231** [comment]
That's cool, I'd rather see a customization overlay solution over the current limited and buggy setup. 👍

**Comment by Alex-231** [comment]
For what it's worth, [here are the scoreboard fixes.](https://github.com/ElDewrito/ElDorito/files/926258/ScaleformScoreboardFixes1.zip) It's not perfect, but it's the best I can get out of the scripts.

**Pull request merged**
