### PR TITLE
Marker changes.

### PR DESCRIPTION
**Pull request by Alex-231**
### Part 1: Added Speaker icon to the markers of speaking players.

Could be refactored.

### CODE REVIEW

**Comment by camden-smallwood** [comment]
Could you explain how your chud_update_player_marker_hook works? Seems a little hairy. What functionality did you have to change from what was already in the exe?

**Comment by Alex-231** [comment]
Update function is called every frame or something.
at hook, eax contains marker secondary color
1 = shooting
2 = speaking
3 = taking damage
It's never 2.  The markers player handle is a parameter of the function,
using that the name of the player is read, if the name of the player is in
there speaking players list then 2 is moved to eax.
It could be refractored, I don't know a lot about networking but this 2
should be sent in a packet, I don't know what packet but I kept seeing
something likes replication entity.

**Comment by RabidSquabbit** [comment]
Nice Work! 0.6 is feature locked but we can look into this for a future update for sure.

**Comment by Alex-231** [comment]
# Update: Added Player Objective Markers

Since It could be a while before this is merged, I decided to add another feature.
I've added a different marker to indicate enemies holding the oddball, flag, or bomb.
Additionally, I've switched to the simple triangle marker texture by default because the current texture is half finished, inconsistent and don't really fit objective icons or names even since it doesn't have a flat top.

I would also like this marker to display on the last man standing in infection, and on VIPs. Although I'm not sure how I'm going to do that.

**Comment by Alex-231** [comment]
Marked as WIP, more fixes to come.

**Comment by Alex-231** [comment]
Commits are pretty self explanatory but a few updates and one more planned.

Done:

* Changed enemy marker functionality to make it easier to identify an enemy while using armour color markers, and to highlight important enemies (like one carrying a flag).
* Moved marker icons like the speaker or flag above names. I think this makes the text easier to read as it doesn't move up and down anymore, and it just looks nicer.
-Fixed an issue where certain icons would appear black or ally blue with armour color markers. Now only player markers change color. (since only players have armour colors)

Todo:

* Fix various issues with markers in assault, like the bomb having no marker in some modes.

**Comment by Alex-231** [comment]
Discard my todo list.

**Comment by Alex-231** [comment]
# New Sprites
Spritesheet

---

I didn't like forcing the old markers. So I made a new spritesheet using unused textures. It's also 3x the size of the old spritesheet, so it should look better at higher resolutions too. I had to add a scale value to allow this, fortunately there was a float in chgd I had already made redundant.

This should be my last update. The new bitmap is required just because it's scaled correctly. It can be replaced as long as the scale of the sprites remains.


[The new spritesheet (0x12BB)](https://filebin.net/2h2rh58c84a4icsq/000012BB.dds)
```
Edit 0x12BB
ImportBitmap 0 000012BB.dds
SaveTagChanges
Exit
```

---

New Sprites 1
New Sprites 2
New Sprites 3
New Sprites 4

**Comment by Alex-231** [comment]
Pulled last 62 commits and tested.

**Pull request closed without merging**
