### PR TITLE
Added more inappropriate service tags to the filter list.

### PR DESCRIPTION
**Pull request by Alex-231**
### Proposed changes in this pull request:

1. Added more service tags to the validation filter set.

### Why should this pull request be merged?
Tags like "KYS" are inappropriate and should not be tolerated.

### Have you tested this on your own and/or in a game with other people?
Tested alone.

### CODE REVIEW

**Comment by rodneywells01** [comment]
Probably should try to keep this list alphabetized, so it's easier in the future to scan through and see what has been added.

**Comment by Alex-231** [comment]
I'm planning on moving this list into dewrito prefs and making a client side censor on dany's recommendation. So I'll do it when I get around to implementing that.

**Comment by NoShotz** [comment]
dewrito_prefs.cfg isn't a json, so it won't format well at all

**Comment by Alex-231** [comment]
I'm sure I'll figure something out when I start working on it, whenever that may be.

**Pull request closed without merging**
